name: Sync

on:
  push:
    # Force re-run on push to master
    branches: [master]
  schedule:
  - cron: 0 2 * * *

permissions:
  packages: write


jobs:
  sync:
    strategy:
      matrix:
        image: ['alpine:latest', 'nginx:latest', 'ubuntu:latest']
    runs-on: ubuntu-latest
    steps:
    - name: Login ghcr.io
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: platform-control-plane
        password: ${{ secrets.PLATFORM_CONTROL_PLANE_PAT }}
    - name: Pull original
      run: |
        docker pull ${{ matrix.image }}
    - name:  Push cache
      run: |
        docker tag ${{ matrix.image }} ghcr.io/neuro-inc/${{ matrix.image }}
        docker push ghcr.io/neuro-inc/${{ matrix.image }}
